name: Build and Analyze Scan

on:
  push:
    branches:
      - master

jobs:
  build_analyze_scan:
    name: Buid
    runs-on: ubuntu-latest  #[self-hosted]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.11
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Docker Buid and Push
        env:
          DOCKER_CLI_ACI: 1

        run: |
          docker-compose -f docker-compose.yml build
          docker tag mlops_project_app:latest ashutoshk12/mlops_project_app:latest
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker push ashutoshk12/mlops_project_app:latest
        
